### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by rakekniven** [fractava/biblio#469]
Many many strings at Transifex are inside of square brackets.

Are they placeholders?
If not, why using brackets. Translators have no context and will just copy the string or do not translate.

Example:
https://github.com/fractava/biblio/blob/555079bbcc2e7da9eff8de59bce0c557e8e6312b/src/store/nomenclature.js#L339

**Comment by JonathanTreffler** [comment]
This is used as a placeholder in the history view, if the customer does not exist anymore, but a history entry still points to the id. That results in the mentioned placeholder being used as the customerName variable for the strings there: https://github.com/fractava/biblio/blob/555079bbcc2e7da9eff8de59bce0c557e8e6312b/src/store/nomenclature.js#L382

But you are correct, that this might be confusing to some translators, I should probably just add the brackets in the code outside the translation string, so the translators don't have to thing about them, since it is not really language specific.
Sorry for the confusion and thank you very much for your effort to bring this problem to my attention.

**Comment by JonathanTreffler** [comment]
I added source comments, closing :)
